In [ ]:
import pandas as pd
import numpy as np

## Upload Data

In [ ]:
file = "https://drive.google.com/uc?id=1-fPwE---eTd-PgIcvrE-fID90lYgfBmR"
data_airlines = pd.read_csv(file)

In [ ]:
file = "https://drive.google.com/uc?id=1A4ZNp1bhGraJzQO9_h6S--vvWhdfQwha"
data_airports = pd.read_csv(file)

In [ ]:
file = "https://drive.google.com/uc?id=1NqbD2btmZGlpc029LNBuNSmcuZHtfCea"
data_flights = pd.read_csv(file)

## Penanganan Nilai Hilang (Missing Values) dan menghapus kolom yang tidak terpakai

In [ ]:
data_airlines = data_airlines.drop(columns=['Unnamed: 0'])

In [ ]:
data_airlines.isnull().sum()

carrier    0
name       0
dtype: int64

In [ ]:
data_airports = data_airports.drop(columns=['Unnamed: 0','alt','tz','dst','tzone'])

In [ ]:
data_airports.isnull().sum()

faa     0
name    0
lat     0
lon     0
dtype: int64

In [ ]:
data_flights = data_flights.drop(columns=['Unnamed: 0','dep_time','sched_dep_time','arr_time','sched_arr_time','hour','minute','time_hour'])

In [ ]:
data_flights.isnull().sum()

year            0
month           0
day             0
dep_delay    8255
arr_delay    9430
carrier         0
flight          0
tailnum      2512
origin          0
dest            0
air_time     9430
distance        0
dtype: int64

In [ ]:
data_flights.dropna(subset=['dep_delay', 'arr_delay', 'air_time', 'tailnum'], inplace=True)

In [ ]:
data_flights.isnull().sum()

year         0
month        0
day          0
dep_delay    0
arr_delay    0
carrier      0
flight       0
tailnum      0
origin       0
dest         0
air_time     0
distance     0
dtype: int64

## Normalisasi Tipe Data

In [ ]:
data_airlines.dtypes

carrier    object
name       object
dtype: object

In [ ]:
data_airports.dtypes

faa      object
name     object
lat     float64
lon     float64
dtype: object

In [ ]:
data_flights.dtypes

year           int64
month          int64
day            int64
dep_delay    float64
arr_delay    float64
carrier       object
flight         int64
tailnum       object
origin        object
dest          object
air_time     float64
distance       int64
dtype: object

In [ ]:
data_flights['dep_delay'] = data_flights['dep_delay'].astype(int)
data_flights['arr_delay'] = data_flights['arr_delay'].astype(int)
data_flights['air_time'] = data_flights['air_time'].astype(int)

In [ ]:
data_flights['full_date'] = pd.to_datetime(data_flights[['year', 'month', 'day']])

In [ ]:
data_flights.dtypes

year                  int64
month                 int64
day                   int64
dep_delay             int64
arr_delay             int64
carrier              object
flight                int64
tailnum              object
origin               object
dest                 object
air_time              int64
distance              int64
full_date    datetime64[ns]
dtype: object

## Menggabungkan Dataset

In [ ]:
flights_merged = pd.merge(data_flights, data_airlines.rename(columns={'name': 'airline_name'}), on='carrier', how='left')
flights_merged

,year,month,day,dep_delay,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,full_date,airline_name
0,2013,1,1,2,11,UA,1545,N14228,EWR,IAH,227,1400,2013-01-01,United Air Lines Inc.
1,2013,1,1,4,20,UA,1714,N24211,LGA,IAH,227,1416,2013-01-01,United Air Lines Inc.
2,2013,1,1,2,33,AA,1141,N619AA,JFK,MIA,160,1089,2013-01-01,American Airlines Inc.
3,2013,1,1,-1,-18,B6,725,N804JB,JFK,BQN,183,1576,2013-01-01,JetBlue Airways
4,2013,1,1,-6,-25,DL,461,N668DN,LGA,ATL,116,762,2013-01-01,Delta Air Lines Inc.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327341,2013,9,30,-5,-17,B6,1816,N354JB,JFK,SYR,41,209,2013-09-30,JetBlue Airways
327342,2013,9,30,-10,-20,B6,2002,N281JB,JFK,BUF,52,301,2013-09-30,JetBlue Airways
327343,2013,9,30,-5,-16,B6,486,N346JB,JFK,ROC,47,264,2013-09-30,JetBlue Airways
327344,2013,9,30,12,1,B6,718,N565JB,JFK,BOS,33,187,2013-09-30,JetBlue Airways
327345,2013,9,30,-10,-25,B6,745,N516JB,JFK,PSE,196,1617,2013-09-30,JetBlue Airways

In [ ]:
airports_origin_renamed = data_airports.rename(columns={
    'faa': 'origin',
    'name': 'origin_airport_name',
    'lat': 'origin_lat',
    'lon': 'origin_lon',
})
flights_merged = pd.merge(flights_merged, airports_origin_renamed, on='origin', how='left')
flights_merged

,year,month,day,dep_delay,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,full_date,airline_name,origin_airport_name,origin_lat,origin_lon
0,2013,1,1,2,11,UA,1545,N14228,EWR,IAH,227,1400,2013-01-01,United Air Lines Inc.,Newark Liberty Intl,40.692500,-74.168667
1,2013,1,1,4,20,UA,1714,N24211,LGA,IAH,227,1416,2013-01-01,United Air Lines Inc.,La Guardia,40.777245,-73.872608
2,2013,1,1,2,33,AA,1141,N619AA,JFK,MIA,160,1089,2013-01-01,American Airlines Inc.,John F Kennedy Intl,40.639751,-73.778925
3,2013,1,1,-1,-18,B6,725,N804JB,JFK,BQN,183,1576,2013-01-01,JetBlue Airways,John F Kennedy Intl,40.639751,-73.778925
4,2013,1,1,-6,-25,DL,461,N668DN,LGA,ATL,116,762,2013-01-01,Delta Air Lines Inc.,La Guardia,40.777245,-73.872608
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327341,2013,9,30,-5,-17,B6,1816,N354JB,JFK,SYR,41,209,2013-09-30,JetBlue Airways,John F Kennedy Intl,40.639751,-73.778925
327342,2013,9,30,-10,-20,B6,2002,N281JB,JFK,BUF,52,301,2013-09-30,JetBlue Airways,John F Kennedy Intl,40.639751,-73.778925
327343,2013,9,30,-5,-16,B6,486,N346JB,JFK,ROC,47,264,2013-09-30,JetBlue Airways,John F Kennedy Intl,40.639751,-73.778925
327344,2013,9,30,12,1,B6,718,N565JB,JFK,BOS,33,187,2013-09-30,JetBlue Airways,John F Kennedy Intl,40.639751,-73.778925
327345,2013,9,30,-10,-25,B6,745,N516JB,JFK,PSE,196,1617,2013-09-30,JetBlue Airways,John F Kennedy Intl,40.639751,-73.778925

In [ ]:
airports_dest_renamed = data_airports.rename(columns={
    'faa': 'dest',
    'name': 'dest_airport_name',
    'lat': 'dest_lat',
    'lon': 'dest_lon',
})
flights_merged = pd.merge(flights_merged, airports_dest_renamed, on='dest', how='left')
flights_merged

,year,month,day,dep_delay,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,full_date,airline_name,origin_airport_name,origin_lat,origin_lon,dest_airport_name,dest_lat,dest_lon
0,2013,1,1,2,11,UA,1545,N14228,EWR,IAH,227,1400,2013-01-01,United Air Lines Inc.,Newark Liberty Intl,40.692500,-74.168667,George Bush Intercontinental,29.984433,-95.341442
1,2013,1,1,4,20,UA,1714,N24211,LGA,IAH,227,1416,2013-01-01,United Air Lines Inc.,La Guardia,40.777245,-73.872608,George Bush Intercontinental,29.984433,-95.341442
2,2013,1,1,2,33,AA,1141,N619AA,JFK,MIA,160,1089,2013-01-01,American Airlines Inc.,John F Kennedy Intl,40.639751,-73.778925,Miami Intl,25.793250,-80.290556
3,2013,1,1,-1,-18,B6,725,N804JB,JFK,BQN,183,1576,2013-01-01,JetBlue Airways,John F Kennedy Intl,40.639751,-73.778925,NaN,NaN,NaN
4,2013,1,1,-6,-25,DL,461,N668DN,LGA,ATL,116,762,2013-01-01,Delta Air Lines Inc.,La Guardia,40.777245,-73.872608,Hartsfield Jackson Atlanta Intl,33.636719,-84.428067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327341,2013,9,30,-5,-17,B6,1816,N354JB,JFK,SYR,41,209,2013-09-30,JetBlue Airways,John F Kennedy Intl,40.639751,-73.778925,Syracuse Hancock Intl,43.111187,-76.106311
327342,2013,9,30,-10,-20,B6,2002,N281JB,JFK,BUF,52,301,2013-09-30,JetBlue Airways,John F Kennedy Intl,40.639751,-73.778925,Buffalo Niagara Intl,42.940525,-78.732167
327343,2013,9,30,-5,-16,B6,486,N346JB,JFK,ROC,47,264,2013-09-30,JetBlue Airways,John F Kennedy Intl,40.639751,-73.778925,Greater Rochester Intl,43.118866,-77.672389
327344,2013,9,30,12,1,B6,718,N565JB,JFK,BOS,33,187,2013-09-30,JetBlue Airways,John F Kennedy Intl,40.639751,-73.778925,General Edward Lawrence Logan Intl,42.364347,-71.005181
327345,2013,9,30,-10,-25,B6,745,N516JB,JFK,PSE,196,1617,2013-09-30,JetBlue Airways,John F Kennedy Intl,40.639751,-73.778925,NaN,NaN,NaN

In [ ]:
flights_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 327346 entries, 0 to 327345
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   year                 327346 non-null  int64
 1   month                327346 non-null  int64
 2   day                  327346 non-null  int64
 3   dep_delay            327346 non-null  int64
 4   arr_delay            327346 non-null  int64
 5   carrier              327346 non-null  object
 6   flight               327346 non-null  int64
 7   tailnum              327346 non-null  object
 8   origin               327346 non-null  object
 9   dest                 327346 non-null  object
 10  air_time             327346 non-null  int64
 11  distance             327346 non-null  int64
 12  full_date            327346 non-null  datetime64[ns]
 13  airline_name         327346 non-null  object
 14  origin_airport_name  327346 non-null  object
 15  origin_lat           327346 non-null  float64
 16  origin_lon           327346 non-null  float64
 17  dest_airport_name    319809 non-null  object
 18  dest_lat             319809 non-null  float64
 19  dest_lon             319809 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(8), object(7)
memory usage: 49.9+ MB

## Penanganan Nilai Hilang (Missing Values) pada data baru, dan menambahkan kolom yang diperlukan

In [ ]:
flights_merged.isnull().sum()

year                      0
month                     0
day                       0
dep_delay                 0
arr_delay                 0
carrier                   0
flight                    0
tailnum                   0
origin                    0
dest                      0
air_time                  0
distance                  0
full_date                 0
airline_name              0
origin_airport_name       0
origin_lat                0
origin_lon                0
dest_airport_name      7537
dest_lat               7537
dest_lon               7537
dtype: int64

In [ ]:
flights_merged.dropna(subset=['dest_airport_name', 'dest_lat', 'dest_lon'], inplace=True)

In [ ]:
flights_merged['is_delayed_dep'] = flights_merged['dep_delay'] > 0
flights_merged['is_delayed_arr'] = flights_merged['arr_delay'] > 0

In [ ]:
flights_merged['route'] = flights_merged['origin_airport_name'] + ' to ' + flights_merged['dest_airport_name']

In [ ]:
flights_merged.describe()

,year,month,day,dep_delay,arr_delay,flight,air_time,distance,full_date,origin_lat,origin_lon,dest_lat,dest_lon
count,319809.0,319809.000000,319809.000000,319809.000000,319809.000000,319809.000000,319809.000000,319809.000000,319809,319809.000000,319809.000000,319809.000000,319809.000000
mean,2013.0,6.569362,15.737768,12.620939,6.986889,1969.176243,149.562254,1035.369427,2013-07-03 07:43:44.447716864,40.702297,-73.949408,35.974400,-89.606263
min,2013.0,1.000000,1.000000,-43.000000,-86.000000,1.000000,20.000000,80.000000,2013-01-01 00:00:00,40.639751,-74.168667,21.318681,-157.922428
25%,2013.0,4.000000,8.000000,-5.000000,-17.000000,546.000000,81.000000,502.000000,2013-04-05 00:00:00,40.639751,-74.168667,32.896828,-95.341442
50%,2013.0,7.000000,16.000000,-2.000000,-5.000000,1501.000000,127.000000,828.000000,2013-07-04 00:00:00,40.692500,-73.872608,36.080056,-83.994028
75%,2013.0,10.000000,23.000000,11.000000,14.000000,3459.000000,184.000000,1372.000000,2013-10-01 00:00:00,40.777245,-73.778925,41.411689,-80.152750
max,2013.0,12.000000,31.000000,1301.000000,1272.000000,8500.000000,695.000000,4983.000000,2013-12-31 00:00:00,40.777245,-73.778925,61.174361,-68.828139
std,0.0,3.412153,8.776202,40.264088,44.835239,1629.769448,94.482205,739.580448,NaN,0.055427,0.169141,5.745137,15.046796

## Menangani Outlier

In [ ]:
def cap_outliers_iqr(series):
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return series.clip(lower=lower_bound, upper=upper_bound)

flights_merged['dep_delay'] = cap_outliers_iqr(flights_merged['dep_delay'])
flights_merged['arr_delay'] = cap_outliers_iqr(flights_merged['arr_delay'])
flights_merged['air_time'] = cap_outliers_iqr(flights_merged['air_time'])

In [ ]:
flights_merged.describe()

,year,month,day,dep_delay,arr_delay,flight,air_time,distance,full_date,origin_lat,origin_lon,dest_lat,dest_lon
count,319809.0,319809.000000,319809.000000,319809.000000,319809.000000,319809.000000,319809.000000,319809.000000,319809,319809.000000,319809.000000,319809.000000,319809.000000
mean,2013.0,6.569362,15.737768,4.963678,1.783308,1969.176243,148.202474,1035.369427,2013-07-03 07:43:44.447716864,40.702297,-73.949408,35.974400,-89.606263
min,2013.0,1.000000,1.000000,-29.000000,-63.500000,1.000000,20.000000,80.000000,2013-01-01 00:00:00,40.639751,-74.168667,21.318681,-157.922428
25%,2013.0,4.000000,8.000000,-5.000000,-17.000000,546.000000,81.000000,502.000000,2013-04-05 00:00:00,40.639751,-74.168667,32.896828,-95.341442
50%,2013.0,7.000000,16.000000,-2.000000,-5.000000,1501.000000,127.000000,828.000000,2013-07-04 00:00:00,40.692500,-73.872608,36.080056,-83.994028
75%,2013.0,10.000000,23.000000,11.000000,14.000000,3459.000000,184.000000,1372.000000,2013-10-01 00:00:00,40.777245,-73.778925,41.411689,-80.152750
max,2013.0,12.000000,31.000000,35.000000,60.500000,8500.000000,338.500000,4983.000000,2013-12-31 00:00:00,40.777245,-73.778925,61.174361,-68.828139
std,0.0,3.412153,8.776202,14.717989,26.936554,1629.769448,90.672994,739.580448,NaN,0.055427,0.169141,5.745137,15.046796

## Menyimpan Data yang Sudah Diproses

In [ ]:
flights_merged.to_excel("Terakhir nih.xlsx", index=False)
from google.colab import files
files.download("Terakhir nih.xlsx")